<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>单元测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 80%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">单元测试报告</h1>
<p class='attribute'><strong>测试人员 : </strong> 最棒QA</p>
<p class='attribute'><strong>开始时间 : </strong> 2018-10-31 14:58:29</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:03.546000</p>
<p class='attribute'><strong>测试结果 : </strong> 共 24，通过 1，错误 23，通过率= 4.17%</p>

<p class='description'></p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 4.17% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 0 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 1 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 24 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 14px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='errorClass warning'>
    <td>GetYTXAccountLoginStatus.GetYTXAccountLoginStatus: 查看登录状态</td>
    <td class="text-center">3</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',3)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_getYTXAccountLoginStatus</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse in">
    <pre>
    
ft1_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[861]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[100]
&lt;type 'unicode'&gt;
检查点失败，实际结果[请重新登录]，预期结果[请求成功！]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\GetYTXAccountLoginStatus.py", line 21, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_getYTXAccountLoginStatus</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse in">
    <pre>
    
ft1_2: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[120]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[100]
&lt;type 'unicode'&gt;
检查点失败，实际结果[请重新登录]，预期结果[请求成功！]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\GetYTXAccountLoginStatus.py", line 21, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_getYTXAccountLoginStatus</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse in">
    <pre>
    
ft1_3: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[121]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[100]
&lt;type 'unicode'&gt;
检查点失败，实际结果[请重新登录]，预期结果[请求成功！]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\GetYTXAccountLoginStatus.py", line 21, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>List.List: 获取科室列表</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',1)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='ft2_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse in">
    <pre>
    
ft2_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[112]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\List.py", line 18, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>GetConcernDoctorList.GetConcernDoctorList: 获取关联医生列表</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',1)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_getConcernDoctorList</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse in">
    <pre>
    
ft3_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[105]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\GetConcernDoctorList.py", line 19, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>GetOnLineCommodityDetail.GetOnLineCommodityDetail: 获取医生在线咨询服务</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c4',2)" class="detail" id='c4'>详细</a></td>
</tr>

<tr id='ft4_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_getOnLineCommodityDetail</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_1'>错误</button>
    <div id='div_ft4_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_1'>错误</button>
    <div id='div_ft4_1' class="collapse in">
    <pre>
    
ft4_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[159]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\GetOnLineCommodityDetail.py", line 38, in test_getOnLineCommodityDetail
    cl.save("commoditySubType",cl.json.get("data")['onlineCommodityList'][1]['commoditySubType'])
TypeError: 'NoneType' object has no attribute '__getitem__'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_getOnLineCommodityDetail</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_2'>错误</button>
    <div id='div_ft4_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_2'>错误</button>
    <div id='div_ft4_2' class="collapse in">
    <pre>
    
ft4_2: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[159]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\GetOnLineCommodityDetail.py", line 19, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>Put.Put: put</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c5',1)" class="detail" id='c5'>详细</a></td>
</tr>

<tr id='ft5_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_put</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_1'>错误</button>
    <div id='div_ft5_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_1'>错误</button>
    <div id='div_ft5_1' class="collapse in">
    <pre>
    
ft5_1: {}
None
{'data': {'hasPriceFavorable': None, 'commodityId': None, 'doctor': {'name': None, 'userId': None, 'imgPath': None, 'hospitalName': None, 'itemName': None, 'titleName': None}, 'orderType': None, 'priceId': None, 'prevPage': 'consult_my', 'processDefinitionId': None}, 'key': 'mall_service_apply_form', 'Yb-Yh-Token': 'c187181d37defebf921f1c37597b2177', 'Yb-Yh-Client': '0'}
检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[156]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\Put.py", line 17, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>Get.Get: get</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c6',1)" class="detail" id='c6'>详细</a></td>
</tr>

<tr id='ft6_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_get</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft6_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft6_1'>错误</button>
    <div id='div_ft6_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft6_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft6_1'>错误</button>
    <div id='div_ft6_1' class="collapse in">
    <pre>
    
ft6_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[103]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\Get.py", line 16, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>InitForm.InitForm: 初始化表单</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c7',2)" class="detail" id='c7'>详细</a></td>
</tr>

<tr id='ft7_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_initForm</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft7_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft7_1'>错误</button>
    <div id='div_ft7_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft7_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft7_1'>错误</button>
    <div id='div_ft7_1' class="collapse in">
    <pre>
    
ft7_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[127]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\InitForm.py", line 28, in test_initForm
    cl.save("templateId", cl.json.get("data")['formTemplate']['id'])
TypeError: 'NoneType' object has no attribute '__getitem__'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft7_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_initForm</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft7_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft7_2'>错误</button>
    <div id='div_ft7_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft7_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft7_2'>错误</button>
    <div id='div_ft7_2' class="collapse in">
    <pre>
    
ft7_2: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[127]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\InitForm.py", line 17, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>GetPatientlist.GetPatientlist: 获取医生在线咨询服务</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c8',1)" class="detail" id='c8'>详细</a></td>
</tr>

<tr id='ft8_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_getPatientlist</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft8_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft8_1'>错误</button>
    <div id='div_ft8_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft8_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft8_1'>错误</button>
    <div id='div_ft8_1' class="collapse in">
    <pre>
    
ft8_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[112]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[100]
检查点失败，实际结果[请重新登录]，预期结果[获取患者列表成功！]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\GetPatientlist.py", line 17, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>Pre.Pre: pre</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c9',2)" class="detail" id='c9'>详细</a></td>
</tr>

<tr id='ft9_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_pre</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_1'>错误</button>
    <div id='div_ft9_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_1'>错误</button>
    <div id='div_ft9_1' class="collapse in">
    <pre>
    
ft9_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[101]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\Pre.py", line 17, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_pre</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_2'>错误</button>
    <div id='div_ft9_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_2'>错误</button>
    <div id='div_ft9_2' class="collapse in">
    <pre>
    
ft9_2: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[29]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\Pre.py", line 17, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>CheckPatient.CheckPatient: 检查用户信息</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c10',1)" class="detail" id='c10'>详细</a></td>
</tr>

<tr id='ft10_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_checkPatient</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft10_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft10_1'>错误</button>
    <div id='div_ft10_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft10_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft10_1'>错误</button>
    <div id='div_ft10_1' class="collapse in">
    <pre>
    
ft10_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[104]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\CheckPatient.py", line 17, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>GetAssistantAccount.GetAssistantAccount: 获取随访账号</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c11',1)" class="detail" id='c11'>详细</a></td>
</tr>

<tr id='ft11_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_getAssistantAccount</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_1'>错误</button>
    <div id='div_ft11_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_1'>错误</button>
    <div id='div_ft11_1' class="collapse in">
    <pre>
    
ft11_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[112]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[100]
检查点失败，实际结果[请重新登录]，预期结果[请求成功！]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\GetAssistantAccount.py", line 17, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>StartProcess.StartProcess: 开启流程</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c12',2)" class="detail" id='c12'>详细</a></td>
</tr>

<tr id='ft12_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_startProcess</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft12_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft12_1'>错误</button>
    <div id='div_ft12_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft12_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft12_1'>错误</button>
    <div id='div_ft12_1' class="collapse in">
    <pre>
    
ft12_1: {'Yb-Yh-Token': 'c187181d37defebf921f1c37597b2177', 'Yb-Yh-Client': '0'}
检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[82]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\StartProcess.py", line 51, in test_startProcess
    cl.save("processInstanceId",cl.json.get('data')["processInstanceId"])
TypeError: 'NoneType' object has no attribute '__getitem__'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft12_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_startProcess</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft12_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft12_2'>错误</button>
    <div id='div_ft12_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft12_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft12_2'>错误</button>
    <div id='div_ft12_2' class="collapse in">
    <pre>
    
ft12_2: {'Yb-Yh-Token': 'c187181d37defebf921f1c37597b2177', 'Yb-Yh-Client': '0'}
检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[82]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\StartProcess.py", line 20, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>SaveOrder.SaveOrder: 开启流程</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c13',1)" class="detail" id='c13'>详细</a></td>
</tr>

<tr id='ft13_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_saveOrder</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft13_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft13_1'>错误</button>
    <div id='div_ft13_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft13_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft13_1'>错误</button>
    <div id='div_ft13_1' class="collapse in">
    <pre>
    
ft13_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[253]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[100]
检查点失败，实际结果[请重新登录]，预期结果[保存商城订单信息成功]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\SaveOrder.py", line 18, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='passClass warning'>
    <td>GetImMsgTemplateInfo.GetImMsgTemplateInfo: 获取IM消息模板信息</td>
    <td class="text-center">1</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c14',1)" class="detail" id='c14'>详细</a></td>
</tr>

<tr id='pt14_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_getImMsgTemplateInfo</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt14_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt14_1'>通过</button>
    <div id='div_pt14_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt14_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt14_1'>通过</button>
    <div id='div_pt14_1' class="collapse in">
    <pre>
    
pt14_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[133]，预期结果[&lt;1000]
检查点成功，实际结果[0]，预期结果[0]
检查点成功，实际结果[请求成功！]，预期结果[请求成功！]


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>InitIM.InitIM: 获取IM消息模板信息</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c15',1)" class="detail" id='c15'>详细</a></td>
</tr>

<tr id='ft15_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_initIM</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_1'>错误</button>
    <div id='div_ft15_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_1'>错误</button>
    <div id='div_ft15_1' class="collapse in">
    <pre>
    
ft15_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[96]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[100]
检查点失败，实际结果[请重新登录]，预期结果[请求成功！]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\InitIM.py", line 18, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>GetConversationInfo.GetConversationInfo: 获取会话</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c16',1)" class="detail" id='c16'>详细</a></td>
</tr>

<tr id='ft16_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_getConversationInfo</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft16_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft16_1'>错误</button>
    <div id='div_ft16_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft16_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft16_1'>错误</button>
    <div id='div_ft16_1' class="collapse in">
    <pre>
    
ft16_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[147]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[获取会话成功!]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\GetConversationInfo.py", line 17, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>GetHistoryMsgByMsgTime.GetHistoryMsgByMsgTime: 获取历史会话</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c17',1)" class="detail" id='c17'>详细</a></td>
</tr>

<tr id='ft17_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_getHistoryMsgByMsgTime</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft17_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft17_1'>错误</button>
    <div id='div_ft17_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft17_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft17_1'>错误</button>
    <div id='div_ft17_1' class="collapse in">
    <pre>
    
ft17_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[134]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[请求成功！]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\GetHistoryMsgByMsgTime.py", line 17, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>ResetUnreadMsgCount.ResetUnreadMsgCount: 获取未读消息数</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c18',1)" class="detail" id='c18'>详细</a></td>
</tr>

<tr id='ft18_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_resetUnreadMsgCount</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_1'>错误</button>
    <div id='div_ft18_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_1'>错误</button>
    <div id='div_ft18_1' class="collapse in">
    <pre>
    
ft18_1: 检查点成功，实际结果[200]，预期结果[200]
检查点成功，实际结果[250]，预期结果[&lt;1000]
检查点失败，实际结果[99]，预期结果[0]
检查点失败，实际结果[请重新登录]，预期结果[未读消息清零成功!]
Traceback (most recent call last):
  File "F:\hyj\pytho\yb\ResetUnreadMsgCount.py", line 17, in tearDown
    self.client.result()
  File "F:\hyj\pytho\yb\client.py", line 137, in result
    self.assertTrue(False,'断言出现错误')
AssertionError: 断言出现错误


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>24</td>
    <td>1</td>
    <td>0</td>
    <td>23</td>
    <td>通过率：4.17%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
